#!/usr/bin/env bash
echo "== create bucket"

# Chcek for bucket name
if [ -z "$1" ]; then
  echo "Needs bucket name eg ./bucket my-bucket"
  exit: 1
fi

BUCKET_NAME=$1

aws s3api create-bucket \
--bucket $BUCKET_NAME \
--query Location \
--output text