AWSTemplateFormatVersion: "2010-09-09"
Description: A simple s3 bucket
Resources:
  S3Bucket:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html
    Type: 'AWS::S3::Bucket'
    # We don't need to supply Bucket Name as AWS will auto gen a random one
    